services:
  - type: web
    name: flashcard-idiomas-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.0"
